name: Deno Check

on:
  push
  
permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 20
    services:
      postgres:
        image: aa8y/postgres-dataset:world
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.31.1

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run Deno Check 
        run: deno check src/mod.ts

      - name: Run tests
        run: deno test --check -A --parallel
